Notebook update: Timeseries Tools
cal-adapt/cae-notebooks pull request #18
Opened 2022-10-14 15:42 UTC by vicford

Splitting PRs per notebook, so apologies in advance for the multiple review requests. 

This PR updates our timeseries notebook for export and cleaned up some markdown text size. 

**To test**: 
1. Run through notebook
2. Check that export works for the timeseries data as a:
-  **netcdf**
-  **csv**
 
 GeoTIFF will not work as it is a timeseries, and the markdown text is updated to reflect this.

2022-10-14 20:43 UTC, gdicecco approved these changes
I'm not sure how long this is taking for other people, but 3 & 9 km here for ~50 years of data w/ no spatial subsetting was taking more than 20 minutes to compute (that's when I quit kernel). This shouldn't preclude these changes from merging to main, but I think we eventually want a dask cluster chunk here too unless that wouldn't help with these particular computations.

Otherwise, no issues w/ select, explore, export!

2022-10-14 20:49 UTC, thenaomig commented
Yes, agree that we should also add a chunk of code for dask gateway to this
particular notebook.

On Fri, Oct 14, 2022 at 1:44 PM Grace Di Cecco ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> I'm not sure how long this is taking for other people, but 3 & 9 km here
> for ~50 years of data w/ no spatial subsetting was taking more than 20
> minutes to process (that's when I quit kernel). This shouldn't preclude
> these changes from merging to main, but I think we eventually want a dask
> cluster chunk here too unless that wouldn't help with these particular
> computations.
>
> Otherwise, no issues w/ select, explore, export!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cal-adapt/cae-notebooks/pull/18#pullrequestreview-1142985187>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXIHRDIL3D7OAU4NM6BU4LWDHAZRANCNFSM6AAAAAARFLMQT4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-10-14 21:57 UTC, vicford commented
Added in a gateway cluster for this notebook - thanks for the suggestion Grace & Naomi! 

Will point out that working with daily data (20 years at 9km scale, for a county selection) will crash the kernel for me on testing this with no memory. Will revisit.

2022-10-17 21:52 UTC, bethmints requested changes
just update to that text I sent you - sorry I couldn't push the PR myself, I think I have to generate a new key pair

2022-10-18 13:58 UTC, vicford commented
> just update to that text I sent you

It's in! Thanks Beth

2022-10-18 17:38 UTC, elehmer approved these changes
LGTM! Runs well and don't see any issues on the HUB with cluster.

2022-10-20 16:46 UTC, merged