replace location with selections
cal-adapt/cae-notebooks pull request #49
Opened 2023-04-28 19:13 UTC by nicolejkeeney

DRAFT-- do not review (yet!). I want to look over one more time before others do. 

This PR should be run in the climakitae branch `combine` (same name as this branch). That branch combines `app.selections` and `app.location`, such that it's just `app.selections` now, which contains both data and location information. I had to modify notebooks that worked directly with `app.location` to function with this new update.

2023-05-01 17:09 UTC, vicford commented on specific_use_cases/DFU_work_in_progress/station_8760s.ipynb
Getting this error in station_8760s notebook in app.select by just switching from `gridded` to `station`

```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pyviz_comms/__init__.py", line 325, in _handle_msg
    self._on_msg(msg)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/viewable.py", line 273, in _on_msg
    doc.unhold()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/document.py", line 799, in unhold
    self.callbacks.unhold()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 396, in unhold
    self.trigger_on_change(event)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 373, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/util/callback_manager.py", line 191, in invoke
    callback(attr, old, new)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 301, in _comm_change
    self._process_events({attr: new})
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 262, in _process_events
    self.param.set_param(**self_events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/param.py", line 444, in link_widget
    self.object.param.set_param(**{p_name: change.new})
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 520, in caller
    return function()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 351, in _depends
    return func(*args,**kw)
  File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 1148, in _update_station_list
    self.station = overlapping_stations
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 316, in _f
    instance_param.__set__(obj, val)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 318, in _f
    return f(self, obj, val)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 984, in __set__
    obj.param._call_watcher(watcher, event)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1645, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 520, in caller
    return function()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 351, in _depends
    return func(*args,**kw)
  File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 1279, in map_view
    return _map_view(selections=self)
  File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 491, in _map_view
    stations_selection_gpd = stations_gpd.loc[
NameError: name 'stations_gpd' is not defined
```

2023-05-01 17:14 UTC, vicford commented on specific_use_cases/DFU_work_in_progress/localization.ipynb
In localization notebook, it's not liking the 'cesm2' call in the app.selections cell (cell 4), presumably because it is something like `wrf_cesm2_r1i1p1f1` (or the appropriate ensemble member now)

```
KeyError: 'cesm2'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_1428/3878577620.py in <module>
     12 
     13 wrf_ds = app.retrieve()
---> 14 wrf_ds = wrf_ds.sel(simulation = 'cesm2').squeeze()
```

2023-05-01 17:17 UTC, vicford commented on specific_use_cases/DFU_work_in_progress/INTRO_annual_consumption_model.ipynb
At app.selections.data_type = "Station" step:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_1501/2723993790.py in <module>
----> 1 app.selections.data_type = "Station"
      2 app.selections.area_subset = "CA Electricity Demand Forecast Zones"
      3 app.selections.cached_area = "SMUD Service Territory"
      4 app.selections.historical_scenario = "Historical Climate"
      5 app.selections.scenario_ssp = ["SSP 3-7.0 -- Business as Usual"]

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in _f(self, obj, val)
    316             instance_param.__set__(obj, val)
    317             return
--> 318         return f(self, obj, val)
    319     return _f
    320 

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in __set__(self, obj, val)
    982                       old=_old, new=val, type=None)
    983         for watcher in watchers:
--> 984             obj.param._call_watcher(watcher, event)
    985         if not obj.param._BATCH_WATCH:
    986             obj.param._batch_call_watchers()

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in _call_watcher(self_, watcher, event)
   1643             event = self_._update_event_type(watcher, event, self_.self_or_cls.param._TRIGGER)
   1644             with batch_watch(self_.self_or_cls, enable=watcher.queued, run=False):
-> 1645                 self_._execute_watcher(watcher, (event,))
   1646 
   1647     def _batch_call_watchers(self_):

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in _execute_watcher(self, watcher, events)
   1625             async_executor(partial(watcher.fn, *args, **kwargs))
   1626         else:
-> 1627             watcher.fn(*args, **kwargs)
   1628 
   1629     def _call_watcher(self_, watcher, event):

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in caller(*events)
    518     else:
    519         def caller(*events):
--> 520             return function()
    521     caller._watcher_name = n
    522     return caller

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in _depends(*args, **kw)
    349     @wraps(func)
    350     def _depends(*args,**kw):
--> 351         return func(*args,**kw)
    352 
    353     deps = list(dependencies)+list(kw.values())

~/src/climakitae/climakitae/selectors.py in _update_station_list(self)
   1146             else:
   1147                 self.param["station"].objects = overlapping_stations
-> 1148                 self.station = overlapping_stations
   1149         elif self.data_type == "Gridded":
   1150             notice = "Set data type to 'Station' to see options"

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in _f(self, obj, val)
    314         instance_param = getattr(obj, '_instance__params', {}).get(self.name)
    315         if instance_param is not None and self is not instance_param:
--> 316             instance_param.__set__(obj, val)
    317             return
    318         return f(self, obj, val)

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in _f(self, obj, val)
    316             instance_param.__set__(obj, val)
    317             return
--> 318         return f(self, obj, val)
    319     return _f
    320 

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in __set__(self, obj, val)
    982                       old=_old, new=val, type=None)
    983         for watcher in watchers:
--> 984             obj.param._call_watcher(watcher, event)
    985         if not obj.param._BATCH_WATCH:
    986             obj.param._batch_call_watchers()

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in _call_watcher(self_, watcher, event)
   1643             event = self_._update_event_type(watcher, event, self_.self_or_cls.param._TRIGGER)
   1644             with batch_watch(self_.self_or_cls, enable=watcher.queued, run=False):
-> 1645                 self_._execute_watcher(watcher, (event,))
   1646 
   1647     def _batch_call_watchers(self_):

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in _execute_watcher(self, watcher, events)
   1625             async_executor(partial(watcher.fn, *args, **kwargs))
   1626         else:
-> 1627             watcher.fn(*args, **kwargs)
   1628 
   1629     def _call_watcher(self_, watcher, event):

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in caller(*events)
    518     else:
    519         def caller(*events):
--> 520             return function()
    521     caller._watcher_name = n
    522     return caller

/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py in _depends(*args, **kw)
    349     @wraps(func)
    350     def _depends(*args,**kw):
--> 351         return func(*args,**kw)
    352 
    353     deps = list(dependencies)+list(kw.values())

~/src/climakitae/climakitae/selectors.py in map_view(self)
   1277     def map_view(self):
   1278         """Create a map of the location selections"""
-> 1279         return _map_view(selections=self)
   1280 
   1281 

~/src/climakitae/climakitae/selectors.py in _map_view(selections)
    489         # Subset the stations gpd to get just the user's selected stations
    490         # We need the stations gpd because it has the coordinates, which will be used to make the plot
--> 491         stations_selection_gpd = stations_gpd.loc[
    492             stations_gpd["station"].isin(selections.station)
    493         ]

NameError: name 'stations_gpd' is not defined
```

2023-05-01 17:18 UTC, vicford commented on explore_warming.ipynb
at app.explore.warming()

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1240/2034446390.py in <module>
----> 1 app.explore.warming_levels()

~/src/climakitae/climakitae/explore.py in warming_levels(self)
     87             var_config=self.var_config,
     88         )
---> 89         return _display_warming_levels(
     90             warming_data,
     91             self.selections,

TypeError: _display_warming_levels() missing 1 required positional argument: 'map_view'
```

2023-05-01 17:19 UTC, vicford requested changes
Some notebooks work totally fine for me, others not -- comments below

Largely looks like a stations_gpd thing and some naming convention, plus the map_view issue in warming levels

2023-05-01 17:32 UTC, nicolejkeeney commented on specific_use_cases/DFU_work_in_progress/localization.ipynb
Ah, I forgot to check this notebook. You're probably right, thanks!

2023-05-02 18:09 UTC, nicolejkeeney commented
Okay, I think (fingers crossed) that everything should be working now, provided it's run in the climakitae branch ```mapview```

2023-05-02 21:50 UTC, nicolejkeeney commented
Update May 2: Beth reviewed localization.ipynb and confirmed it runs as expected.

2023-05-08 14:05 UTC, vicford commented
Update: 
- INTRO works great now
- Localization works great now
- Warming levels works great now (there is a warning at the final figure, but I believe that is resolved with a newer image/switch in the code that I had done previously that we had to roll back for the older image)

Issues:
Station_8760s (in mapview branch):
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1197/2321414481.py in <module>
----> 1 median_year = data.squeeze().map(get_median_8760)

/srv/conda/envs/notebook/lib/python3.9/site-packages/xarray/core/common.py in __getattr__(self, name)
    237                 with suppress(KeyError):
    238                     return source[name]
--> 239         raise AttributeError(
    240             "{!r} object has no attribute {!r}".format(type(self).__name__, name)
    241         )

AttributeError: 'DataArray' object has no attribute 'map'
```

2023-05-09 16:02 UTC, nicolejkeeney commented
> Update:
> 
> * INTRO works great now
> * Localization works great now
> * Warming levels works great now (there is a warning at the final figure, but I believe that is resolved with a newer image/switch in the code that I had done previously that we had to roll back for the older image)
> 
> Issues: Station_8760s (in mapview branch):
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> /tmp/ipykernel_1197/2321414481.py in <module>
> ----> 1 median_year = data.squeeze().map(get_median_8760)
> 
> /srv/conda/envs/notebook/lib/python3.9/site-packages/xarray/core/common.py in __getattr__(self, name)
>     237                 with suppress(KeyError):
>     238                     return source[name]
> --> 239         raise AttributeError(
>     240             "{!r} object has no attribute {!r}".format(type(self).__name__, name)
>     241         )
> 
> AttributeError: 'DataArray' object has no attribute 'map'
> ```

This should hopefully be fixed now

2023-05-09 19:49 UTC, gdicecco approved these changes
For each notebook, I just tried either executing the cell with app.selections and retrieving the object, or for each panel trying a different county subset and retrieving the data. No issues with any of that!

2023-05-09 22:12 UTC, merged