Updates scenario uncertainty language per request
cal-adapt/cae-notebooks pull request #58
Opened 2023-06-19 15:12 UTC by vicford

Small modification to language per Susan request surrounding emissions trajectories for scenario uncertainty

2023-06-19 16:49 UTC, gdicecco requested changes

2023-06-19 16:49 UTC, gdicecco commented on explore_internal_variability.ipynb
> +    "3. <b>Scenario Uncertainty</b>, which arises from differences in outcomes between different emissions trajectories.\n",
"which arises from differences in outcomes between emissions trajectories." ?

2023-06-19 16:49 UTC, gdicecco commented on explore_model_uncertainty.ipynb
> +    "3. **Scenario Uncertainty**, which arises from differences in outcomes between different emissions trajectories\n",
Same as internal variability nb comment

2023-06-19 17:06 UTC, vicford commented
Done! Great catch @gdicecco, I hadn't thought about the different differences (lol)

2023-06-21 17:02 UTC, gdicecco approved these changes

2023-06-21 17:15 UTC, merged